# Generated by Django 2.2.16 on 2023-06-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230206_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts'},
        ),
    ]
